### ISSUE TITLE
How to use useHash flag for callback returns after login from Auth0 dialog

### ISSUE THREAD

**Issue by kushwahashiv** [auth0-samples/auth0-angularjs2-systemjs-sample#40] opened 2016-11-24 10:54 UTC

**Comment by chenkie** [comment] 2016-12-02 20:29
@kushwahashiv there are issues with Angular thinking that the info that comes back in the hash is supposed to be a route. Check this thread for a potential fix: https://github.com/auth0/lock/issues/527

**Comment by kushwahashiv** [comment] 2016-12-03 04:46
I don't think it has any solution. Auth0 seems to be a mess with TypeScript + Angular 2 had to reconsider uses of Auth0 across application lines.

**Comment by chenkie** [comment] 2016-12-03 14:18
Can you provide some more description and an example? Auth0 is fully compatible with Angular 2 so we can sort out what the problem is :)

**Comment by kushwahashiv** [comment] 2016-12-04 05:04
we have used seed app from [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) with useHash set to true and used auth0-lock and @types/auth0-lock but implemented login etc. but it has issue like hashbang urls to callbacks after authentication. Can you please help us creating a sample code in above seed how to use this with useHash in angular 2.

**Comment by chenkie** [comment] 2016-12-06 14:56
There's an issue with redirects when using hashes in Angular 2. The problem is that when the `authResult` comes back in the redirect after authentication, Angular thinks it's a route called `access_token`. One way to solve this is found in the issue linked above. Essentially you listen for when routes are changed and you use `auth0.js` to parse the hash result that is in the URL bar if it exists.

Make sure you have both Lock and `auth0.js`.

```bash
npm install auth0-lock auth0-js --save
```

And then create a method in your auth service to listen for router changes and parse the hash if there is one.

```ts
import { Router } from '@angular/router';
import 'rxjs/add/operator/take';

@Injectable()
export class Auth {

  lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {});
  auth0 = new Auth0({clientID: AUTH0_CLIENT_ID, domain: AUTH0_DOMAIN});

  constructor(private router: Router) {
    this.lock.on('authenticated', authResult => {
      localStorage.setItem('id_token', authResult.idToken);
    });

    this.lock.on('authorization_error', authResult => {
      console.log(authResult);
    });

    this.handleRedirectWithHash();
  }

  private handleRedirectWithHash() {
    this.router.events.take(1).subscribe(event => {
      if (/access_token/.test(event.url) || /error/.test(event.url)) {  

        let authResult = this.auth0.parseHash(window.location.hash);

        if (authResult && authResult.idToken) {
          this.lock.emit('authenticated', authResult);
        }

        if (authResult && authResult.error) {
          this.lock.emit('authorization_error', authResult);
        }
      }
    });
  }
...
```

**Comment by kushwahashiv** [comment] 2016-12-06 16:49
@chenkie thanks for the workaround and we tried using CanActivate but that's not the long term solution. I'm not sure, if Auth0 team has any issue open for this and have near future plan to fix this major bug. if you have any info/update please let us know. Thanks in advance.

**Comment by chenkie** [comment] 2016-12-06 17:06
Can you elaborate on what you mean when you say you tried using `CanActivate`? Which part isn't working right now?

**Comment by kushwahashiv** [comment] 2016-12-06 17:45
We used a [CanActive](https://angular.io/docs/ts/latest/api/router/index/CanActivate-interface.html) to ignore ``access_token``  as below:

```js
import { Location } from '@angular/common';

export class Auth0SkipGuard implements CanActivate {
  canActivate() {
    let index = this.location.path(true).indexOf('access_token');
    if (index === -1) {
      return true;
    } else {
      let result = this.auth0.parseHash(window.location.hash);
      if (result && result.idToken) {
        localStorage.setItem('id_token', JSON.stringify(result.idToken));
       localStorage.setItem('authLoginData', JSON.stringify(result));
      }
      this._router.navigate(['/']);
      return false;
    }
  }
}

export const ROUTES = [
 ...
  {path: '**', component: NoContent, canActivate: [Auth0SkipGuard]}
];
```

**Comment by chenkie** [comment] 2016-12-06 19:29
Can you elaborate on why you're using `CanActivate` for this? On the surface, this doesn't seem like it would work and that it also wouldn't be necessary, but I don't know about your specific implementation details and requirements. Have you tried the `handleRedirectWithHash` method I posted above in your `auth` service? It has worked for others and should work in your case as well.

**Comment by vguillemette** [comment] 2016-12-12 12:52
@chenkie How should I configure my routes to work with your solution? Thank you! :)

**Comment by chenkie** [comment] 2017-05-24 17:35
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-angular-samples) :)

**Closed by chenkie** 2017-05-24 17:35 UTC
