### ISSUE TITLE
JWT must have 3 parts

### ISSUE THREAD

**Issue by krisklosterman** [auth0-samples/auth0-angularjs2-systemjs-sample#39] opened 2016-11-11 21:00 UTC
I cannot figure out how to fix this error:

`Error in ./AppComponent class AppComponent - inline template:10:45 caused by: JWT must have 3 parts`

`error_handler.js:53Error: JWT must have 3 parts
    at JwtHelper.decodeToken (angular2-jwt.js:202)
    at JwtHelper.getTokenExpirationDate (angular2-jwt.js:212)
    at JwtHelper.isTokenExpired (angular2-jwt.js:221)
    at tokenNotExpired (angular2-jwt.js:240)
    at Auth.authenticated (auth.service.ts:27)
    at _View_AppComponent0.detectChangesInternal (component.ngfactory.js:207)
    at _View_AppComponent0.AppView.detectChanges (view.js:219)
    at _View_AppComponent0.DebugAppView.detectChanges (view.js:324)
    at _View_AppComponent_Host0.AppView.detectViewChildrenChanges (view.js:245)
    at _View_AppComponent_Host0.detectChangesInternal (host.ngfactory.js:39)`

I am using angular 2 and have made sure my app.component.ts / auth.service.ts / appt.module.ts / index.html
match the files here

**Comment by krisklosterman** [comment] 2016-11-11 21:10
Ok I stopped the error, by checking in the local storage. There was a id_token that had a value of undefined. Deleting it from local storage stopped the error.

But now I tried to re-login and it sets id_token to undefined again...

**Comment by CristinaNicoleta** [comment] 2017-01-17 22:05
I don't know how was back then, but now it gives me the same error because there is no id_token; it has been replaced with access_token. For correcting the error you must replace in the auth.service.ts id_token with access_token.

**Comment by peterblazejewicz** [comment] 2017-01-18 21:13
@krisklosterman 
could you close this issue? thanks!
The error was expected to be thrown if token was incorrectly saved:
https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L255-L257
There was obviously some small issue with code detail when token was saved into local storage.

**Comment by peterblazejewicz** [comment] 2017-01-18 22:26
Also make sure that token getter reads correct token name from local storage:
```
tokenGetter: (() => localStorage.getItem('access_token')),
```
https://github.com/auth0/angular2-jwt/blob/79ff609bf55e8eff699f14bfb9ca224f51fc5d1d/README.md#configuration-options

**Comment by andreasgrimm** [comment] 2017-02-16 12:35
In Auth0 Portal under `Clients -> <your client> -> Settings -> Advanced Settings -> OAuth` I had the setting `OIDC Conformant` activated which on the client in the Angular2 example led to the error `JWT must have 3 parts`. Deactivating it fixed it.

**Comment by rodneyjoyce** [comment] 2017-02-23 18:53
Hmm I have the same error and the cause is the same (the token is "undefined" in isolated storage). The problem is that it happens randomly - not sure what causes it and only 5 times out of 100 logins.

**Comment by MadEddieFFS** [comment] 2017-03-15 09:29
I am also having this issue when passing the token through the command:
```

  jwtHelper: JwtHelper = new JwtHelper();

loggedIn() {
    console.log('Checking token', this.token);
    return this.jwtHelper.isTokenExpired(this.token);
  }
```

When passing the token through as a string I can't see that the TokenGetter should be used.

**Comment by chenkie** [comment] 2017-05-24 17:35
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-angular-samples) :)

**Closed by chenkie** 2017-05-24 17:35 UTC

**Comment by CaptainDroid** [comment] 2017-05-29 06:55
The problem arises due to an improper storage of the token in the localStorage. While saving the token in the localStorage as `localStorage.setItem('id_token', token);` , now the latest change in angular has modified that to accept a default value of "token" instead of "id_token", so just change "id_token" to "token" everywhere in the setItem and getItem commands (eg. `localStorage.setItem('token', token);` ), and that should most probably solve your problem.

**Comment by prakashbariya** [comment] 2017-08-06 05:18
I have same error. I solve this this error.
Create new API in auth0. give Unique Identifier name. I took "NodeAPI"
I mention below config code.
`auth0 = new auth0.WebAuth({
    clientID: 'Hg3EhAWKgrPrX5UNGqFQA5vTbVGWF',
    domain: 'xyz.auth0.com',
    responseType: 'token id_token',
    audience: 'NodeAPI',
    redirectUri: 'http://localhost:4200/callback',      
    scope: 'openid'
  });`
Happy to help you
